### ISSUE TITLE
这里是不是番茄的前端？

### ISSUE THREAD

**Issue by aooom** [Linho1219/OpenFanqieCore#2]
https://github.com/jeremyjia/Games/tree/master/node1/public/zhipu

祝您顺利！

**Comment by Linho1219** [comment]
番茄简谱的前端代码在官网上是公开的，因此前端不是问题。问题在于后端的渲染器。

此外，我不太理解这个 Games 仓库里面到底是些什么，感觉像是七拼八凑来的代码。

也感谢您的支持。
